"""
main.py
-------
FastAPI application entry point.

Responsibilities:
  1. Create the FastAPI app with metadata (title, version, description).
  2. Configure CORS so the React frontend can communicate with this backend.
  3. Register all API routers under their respective prefixes.
  4. Initialise the SQLite database on startup.
  5. Expose a /health endpoint for quick liveness checks.

Running locally:
    cd backend
    uvicorn app.main:app --reload --port 8000

Interactive API docs (auto-generated by FastAPI):
    http://localhost:8000/docs        ← Swagger UI
    http://localhost:8000/redoc       ← ReDoc
"""
import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.config import settings
from app.database import init_db
from app.api import upload, images, processing, analysis, metadata

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.DEBUG if settings.debug else logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

# ── Lifespan (startup / shutdown) ────────────────────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    """Modern FastAPI lifespan handler (replaces deprecated on_event)."""
    logger.info("Starting %s v%s", settings.app_name, settings.app_version)
    init_db()
    logger.info("Database initialised at %s", settings.database_url)

    # Clear the temp/ processed-images directory on every restart.
    # Design decision: processed images are session-scoped (option b).
    # Original uploads are never touched — only temp/ is wiped.
    import shutil
    temp_dir = settings.processed_dir
    if temp_dir.exists():
        for f in temp_dir.iterdir():
            if f.is_file():
                f.unlink(missing_ok=True)
        logger.info("Cleared %s processed temp files from %s", sum(1 for _ in []), temp_dir)
    temp_dir.mkdir(parents=True, exist_ok=True)
    logger.info("Temp processed dir ready at %s", temp_dir)

    yield
    # shutdown: nothing to do (temp files left as-is until next startup)


# ── FastAPI app ───────────────────────────────────────────────────────────────
app = FastAPI(
    title=settings.app_name,
    version=settings.app_version,
    description=(
        "A professional medical image viewer and analysis tool built with FastAPI "
        "and OpenCV. Designed as an educational portfolio project. "
        "⚠ NOT a clinical diagnostic tool — results carry no medical validity."
    ),
    contact={"name": "Portfolio Project"},
    license_info={"name": "MIT"},
    lifespan=lifespan,
)

# ── CORS ──────────────────────────────────────────────────────────────────────
# Allow the React dev server (Vite default: 5173) to make cross-origin requests.
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.allowed_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Routers ───────────────────────────────────────────────────────────────────
# Upload router lives at /api/images/upload
app.include_router(upload.router, prefix="/api/images", tags=["Upload"])

# Image CRUD + file serving
app.include_router(images.router, prefix="/api/images", tags=["Images"])

# Metadata
app.include_router(metadata.router, prefix="/api/images", tags=["Metadata"])

# Processing (OpenCV operations)
app.include_router(processing.router, prefix="/api/images", tags=["Processing"])

# Analysis + history
app.include_router(analysis.router, prefix="/api/images", tags=["Analysis"])


# ── Health check ──────────────────────────────────────────────────────────────
@app.get("/health", tags=["Health"], summary="API liveness check")
def health_check():
    """
    Returns {"status": "healthy"} when the API is running.
    Used by monitoring tools and frontend startup checks.
    """
    return {
        "status": "healthy",
        "app": settings.app_name,
        "version": settings.app_version,
    }


# ── Root ──────────────────────────────────────────────────────────────────────
@app.get("/", tags=["Root"])
def root():
    return {
        "message": f"Welcome to {settings.app_name}",
        "docs": "/docs",
        "health": "/health",
    }
